title: Shengye (Simon) Wan
logo: ./assets/img/fullbody-shot.jpeg
description: <center> Welcome <span>&#58</span>) </center>
twitter_username: test
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
