title: Shengye Wan
logo: ./assets/img/fullbody-shot.jpeg
remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-include-cache
#accent_image: /assets/img/sidebar-bg.jpg
#accent_color: rgb(79,177,186)
