title: <center> Shengye (Simon) Wan </center>
logo: ./assets/img/fullbody-shot.jpeg
description: <center> Welcome <span>&#58</span>) </center>
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
