title: Shengye Wan
remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-include-cache
  - jekyll-avatar

defaults:
  - scope:
      path:         hydejack/
    values:
      accent_image: /assets/img/hydejack-bg.jpg
      accent_color: rgb(38,139,210)

theme_color:  rgb(25,55,71)

font:         Noto Sans, Helvetica, Arial, sans-serif
font_heading: Roboto Slab, Helvetica, Arial, sans-serif
google_fonts: Roboto+Slab:700|Noto+Sans:400,400i,700,700i
layout: list

author:
  name: Shengye Wan
  picture: /assets/image/fullbody-shot.jpeg
  email: simonsywan@gmail.com
  social:
    #twitter: 
    github: simonwan
  about: |
    Hi, I'm Simon or @simonwan, welcome!

    And welcome again!
    
google_analytics: UA-XXXXXXXX-X
    
