lang:                  en
title: Shengye Wan
# A shorter description for the sidebar.
tagline:               Code • Poker
logo: /assets/img/fullbody-shot.jpeg

remote_theme: hydecorp/hydejack@v9.1.4
plugins:
  - jekyll-include-cache
  - jekyll-avatar

menu:
  - title: Resume
    url:   /resume
  - title: Research
    url:   /research

author:
  name: Shengye Wan
  email: simonsywan@gmail.com
  social:
    #twitter: 
    github: simonwan
  about: |
    Hi, I'm Simon or @simonwan, welcome!

    And welcome again!
    
defaults:
  - scope:
      path:         hydejack/
    values:
      accent_image: /assets/img/hydejack-bg.jpg
      accent_color: rgb(38,139,210)

theme_color:  rgb(25,55,71)
